-- Create the featured_submissions table
create table public.featured_submissions (
    id bigint generated by default as identity primary key,
    content text not null,
    username text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.featured_submissions enable row level security;

-- Create policy to allow insertion for authenticated users
create policy "Enable insert for authenticated users"
    on public.featured_submissions
    for insert
    to public
    with check (true);

-- Create policy to allow reading for all users
create policy "Enable read access for all users"
    on public.featured_submissions
    for select
    to public
    using (true);

-- Create policy to allow deletion for authenticated users
create policy "Enable delete for authenticated users"
    on public.featured_submissions
    for delete
    to public
    using (true);